server:
  port: 8080
  baseUrl: /api/v1

spring:
  config:
    activate:
      on-profile: default
  data:
    mariadb:
      jdbc-url: jdbc:log4jdbc:mariadb://61.75.30.54:3306/sdtdb?characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
      username: sdtdbuser
      password: sdtdbpwd1234
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    oracle:
      jdbc-url: jdbc:log4jdbc:oracle:thin:@172.16.21.60:1521:ERP
      username: comm
      password: comm
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

logging:
  level:
    root: info
  file:
    logLocation: C:/app/eca/log/eca-system.log
    org:
      hibernate:
        SQL: debug
        type : trace

slack:
  webhook:
    url: https://hooks.slack.com/services/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
    channel: eca-system