server:
  port: 8080
  baseUrl: /api/v1

logging:
  level:
    root: info
  file:
    logLocation: C:/app/eca/log/eca-system.log
    org:
      hibernate:
        SQL: debug
        type : trace

slack:
  webhook:
    url: https://hooks.slack.com/services/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
    channel: eca-system