server:
  port: 8080
  baseUrl: /api/v1

spring:
  config:
    activate:
      on-profile: default
  data:
    mariadb:
      jdbc-url: jdbc:log4jdbc:mariadb://3.37.89.243:3306/martDB?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: root
      password: root
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          temp:
            use_jdbc_metadata_defaults: false
        generate-ddl: true

mybatis:
  datasource:
    jdbc-url: jdbc:log4jdbc:oracle:thin:@172.16.21.60:1521:ERP
    username: comm
    password: comm
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    mapperLocation: classpath:mybatis/mapper/**/*.xml
    configLocation: classpath:mybatis/mybatis-config.xml

logging:
  level:
    root: info
  file:
    logLocation: C:/app/eca/log/eca-system.log
    org:
      hibernate:
        SQL: debug
        type : trace

slack:
  webhook:
    url: https://hooks.slack.com/services/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
    channel: eca-system